name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Build w/ Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      uses: actions/checkout@v4
      with:
        node-version: ${{ matrix.node-version }}
      run: npm ci
